apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb
spec:
  selector:
    matchLabels:
      app: mb
  replicas: 2
  template:
    metadata:
      labels:
        app: mb
      annotations:
        iam.amazonaws.com/role: mb-role
    spec:
      containers:
      - name: mb
        image: karlaru/message-board:latest
        ports:
          - name: tcp
            containerPort: 5000

        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: iam-user
                key: AWS_ACCESS_KEY_ID
                optional: false
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: iam-user
                key: AWS_SECRET_ACCESS_KEY
                optional: false


---

apiVersion: v1
kind: Service
metadata:
  name: messageboard
  labels:
    app: mb
spec:
  selector:
    app: mb
  ports:
    - port: 5000
