apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb
spec:
  selector:
    matchLabels:
      app: mb
  replicas: 2
  template:
    metadata:
      labels:
        app: mb
    spec:
      containers:
      - name: mb
        image: karlaru/message-board:latest
        ports:
          - name: tcp
            containerPort: 5000
        volumeMounts:
          - mountPath: /etc/boto.cfg
            name: aws-conf
            subPath: boto.cfg

      volumes:
      - name: aws-conf
        secret:
            secretName: aws-secret
            optional: false

---

apiVersion: v1
kind: Service
metadata:
  name: messageboard
  labels:
    app: mb
spec:
  selector:
    app: mb
  ports:
    - port: 5000
